import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
// if (typeof window !== "undefined") {
//   require("bootstrap/dist/js/bootstrap.bundle.min.js");
// }
import "@/style/icon/tabler-icons/webfont/tabler-icons.css";
import "@/style/icon/feather/css/iconfont.css";
import "@/style/scss/main.scss";
import "@fortawesome/fontawesome-free/css/all.min.css";
import LocationDetector from "../app/components/header/LocationDetector";
import ReduxProvider from "./ReduxProvider"; // ⬅️ add this
const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ReduxProvider>
        <LocationDetector />
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
